
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class JfrmSoporte extends javax.swing.JFrame {

    /**
     * Creates new form JfrmSoporte
     */
    public JfrmSoporte() {
        initComponents();
        this.setTitle("MotherBoard");
        this.setLocationRelativeTo(null);
        this.setSize(600,550);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlblNomPieza = new javax.swing.JLabel();
        jlblPiezas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jblFuncion = new javax.swing.JLabel();
        jblConcepto2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jblConcepto = new javax.swing.JLabel();
        jblConcepto1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jlblNomPieza.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jlblNomPieza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNomPieza.setText("Inicio");

        jlblPiezas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblPiezas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPiezas.setText("Imagen");

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jblFuncion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblFuncion.setForeground(new java.awt.Color(255, 255, 255));
        jblFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jblConcepto2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblConcepto2.setForeground(new java.awt.Color(255, 255, 255));
        jblConcepto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConcepto2.setText("Funcion Principal");
        jblConcepto2.setMaximumSize(new java.awt.Dimension(165, 290));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jblConcepto2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jblConcepto2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblFuncion)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jblConcepto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblConcepto.setForeground(new java.awt.Color(255, 255, 255));
        jblConcepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConcepto.setMaximumSize(new java.awt.Dimension(165, 290));

        jblConcepto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblConcepto1.setForeground(new java.awt.Color(255, 255, 255));
        jblConcepto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConcepto1.setText("Concepto");
        jblConcepto1.setMaximumSize(new java.awt.Dimension(165, 290));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jblConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jblConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblNomPieza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPiezas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlblNomPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes del PC");

        jMenuItem4.setText("Motherboard");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador (CPU)");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Memoria Ram");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem10.setText("Disco Duro (HDD)");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Unidad SSD");
        jMenuItem11.setActionCommand("Unidad SSD");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem8.setText("Fuente de Poder (PSU)");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem12.setText("Tarjeta de Video (GPU)");
        jMenuItem12.setActionCommand("Tarjeta de Video (GPU)");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Tarjeta de Red ");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem7.setText("Cooler del Procesador");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem14.setText("Ventilador del Gabinete");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Tarjeta de Sonido");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Batería CMOS");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Cable SATA");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Cable de Alimentación");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuItem9.setText("BIOS / UEFI");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem19.setText("Acerca del programa. ");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("Créditos");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Cooler del Procesador");
        jlblPiezas.setText("");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cooler.png")));
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Sistema de enfriamiento formado por un disipador y un ventilador instalado sobre el procesador."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Mantener baja la temperatura del procesador para evitar el sobrecalentamiento."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("MotherBoard");
        jlblPiezas.setText("");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/motherboard.png")));
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Es la tarjeta principal de la computadora donde se conectan todos los componentes internos."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Permite la comunicación y conexión entre el procesador, la memoria, el almacenamiento y los demás dispositivos."
        + "</body></html>");
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Procesador");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cpu.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Es el componente encargado de ejecutar instrucciones y realizar los cálculos del sistema."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Procesar la información y coordinar el funcionamiento de todos los componentes de la computadora."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Memoria RAM");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ram.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Es una memoria temporal donde se almacenan los datos de los programas que están en uso."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Permitir el acceso rápido a la información mientras la computadora está funcionando."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Fuente de Poder");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fuente.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Componente que convierte la corriente eléctrica en la energía necesaria para la computadora."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Suministrar energía eléctrica a todos los componentes del equipo."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "¿Desea salir?");
    if (a == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Abriendo");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Guardando");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
        "Esta aplicación fue hecha por Ilan Motta en NetBeans y tiene como objetivo mostrar información de los componentes de una computadora.\n "
                + "El usuario puede seleccionar un componente para ver su nombre, imagen, concepto y función principal. Su funcion es facilitar\n "
                + "aprender de los estudiantes, de una PC de manera práctica y divertida.",
        "Acerca del programa",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
        "Colegio Salesiano Don Bosco\n"
        + "Ilan Emiliano Motta Pérez\n" 
        + "Cuarto Bachillerato D\n"
        + "clave: 22\n"
        + "Computación",
        "Créditos",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Disco Duro (HDD)");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/discoD.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Dispositivo de almacenamiento magnético que guarda datos de forma permanente."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Almacenar el sistema operativo, programas y archivos del usuario."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Unidad SSD");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UniSSD.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Dispositivo de almacenamiento de estado sólido que utiliza memoria flash."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Almacenar datos de forma permanente con mayor velocidad que un disco duro tradicional."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Targeta de Video");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TarVi.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Dispositivo encargado de procesar los gráficos e imágenes que se muestran en el monitor."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Mejorar el rendimiento gráfico y generar imágenes, videos y juegos."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Targeta de Red");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TarRed.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Dispositivo que permite conectar la computadora a una red local o a Internet."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Enviar y recibir datos a través de una red."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Ventilador del Gabinete");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Venti.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Ventilador instalado dentro del gabinete para mejorar la circulación del aire."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Expulsar el aire caliente e introducir aire fresco para enfriar los componentes."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Targeta de Sonido");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TarSO.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Dispositivo encargado del procesamiento del audio de la computadora."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Permitir la reproducción y grabación de sonido mediante altavoces y micrófonos."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Bateria CMOS");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bate.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Pequeña batería ubicada en la placa madre que alimenta la memoria CMOS."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Mantener la fecha, la hora y la configuración del BIOS cuando la computadora está apagada."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Cable de Alimentacion");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ali.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Cable que suministra energía desde la fuente de poder a los componentes internos."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Proporcionar la energía necesaria para el funcionamiento de los dispositivos."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("Cable SATA");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sata.png")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Cable de datos utilizado para conectar discos duros y unidades SSD SATA a la placa madre."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Transferir información entre el dispositivo de almacenamiento y la motherboard."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jlblNomPieza.setText("");
        jlblNomPieza.setText("BIOS/UEFI");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BIOS.jpg")));
        jlblPiezas.setText("");
        jblConcepto.setText("");
        jblConcepto.setText("<html><body style='width: 220px'>"
        + "Firmware almacenado en la placa madre que inicia el hardware antes de cargar el sistema operativo."
        + "</body></html>");
        jblFuncion.setText("");
        jblFuncion.setText("<html><body style='width: 210px'>"
        + "Verificar los componentes del equipo, iniciar el sistema y permitir la configuración del hardware."
        + "</body></html>");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmSoporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jblConcepto;
    private javax.swing.JLabel jblConcepto1;
    private javax.swing.JLabel jblConcepto2;
    private javax.swing.JLabel jblFuncion;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPiezas;
    // End of variables declaration//GEN-END:variables
}
